__: aircloud
comment:
  type: giscus
  script: |
    <script src="https://giscus.app/client.js"
        data-repo="Guailoudou/pages"
        data-repo-id="R_kgDOLZFPxQ"
        data-category="Announcements"
        data-category-id="DIC_kwDOLZFPxc4CdlRm"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="preferred_color_scheme"
        data-lang="zh-CN"
        crossorigin="anonymous"
        async>
    </script>
github_username:    Guailoudou
friends: [
    {
        title: "old",
        href: "https://47.115.207.37/"
    }
]
sidebar_avatar: "https://q1.qlogo.cn/g?b=qq&nk=1241593334&s=640"